# Publish @balq/node by hand from the binaries CI attached to the GitHub
# release `node-v<version>`. Needed because npm accounts with 2FA on writes
# require a passkey/OTP that CI cannot supply.
#
#   .\publish-manual.ps1            # uses the version from package.json
#   .\publish-manual.ps1 -DryRun    # stage everything, publish nothing
#
# Runs in crates/bal-node. Requires `npm` (logged in); the release is public.
param([switch]$DryRun)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot
$pkg = Get-Content package.json -Raw | ConvertFrom-Json
$version = $pkg.version
$tag = "node-v$version"
$platforms = @("win32-x64-msvc", "linux-x64-gnu", "linux-arm64-gnu", "darwin-x64", "darwin-arm64")

Write-Host "release $tag -> staging $($platforms.Count) platform packages"
if (Test-Path rel) { Remove-Item rel -Recurse -Force }
New-Item -ItemType Directory rel | Out-Null
$base = "https://github.com/artemmartyhin/balq/releases/download/$tag"
$files = @("index.js", "index.d.ts") + ($platforms | ForEach-Object { "bal-node.$_.node" })
foreach ($f in $files) {
    try { Invoke-WebRequest "$base/$f" -OutFile "rel$f" }
    catch { throw "cannot download $f from the $tag release — is the CI run complete? ($_)" }
}

# The loader generated by CI and the local one must agree on package names.
Copy-Item rel\index.js index.js -Force
Copy-Item rel\index.d.ts index.d.ts -Force
node test\check-loader.mjs
if ($LASTEXITCODE -ne 0) { throw "loader/optionalDependencies mismatch" }

foreach ($p in $platforms) {
    $dir = "npm\$p"
    if (-not (Test-Path $dir)) { throw "missing $dir — run: npx napi create-npm-dirs" }
    $bin = "rel\bal-node.$p.node"
    if (-not (Test-Path $bin)) { throw "missing $bin in the release" }
    Copy-Item $bin $dir -Force
    $pj = Get-Content "$dir\package.json" -Raw | ConvertFrom-Json
    if ($pj.version -ne $version) { throw "$dir is $($pj.version), expected $version" }
    if ($pkg.optionalDependencies."$($pj.name)" -ne $version) {
        throw "package.json optionalDependencies pins $($pj.name) to $($pkg.optionalDependencies."$($pj.name)"), expected $version"
    }
}

foreach ($p in $platforms) {
    Write-Host "== @balq/node-$p@$version"
    if (-not $DryRun) {
        Push-Location "npm\$p"
        npm publish --access public
        if ($LASTEXITCODE -ne 0) { Pop-Location; throw "publish failed for $p" }
        Pop-Location
    }
}
Write-Host "== @balq/node@$version"
if (-not $DryRun) {
    npm publish --access public
    if ($LASTEXITCODE -ne 0) { throw "publish failed for @balq/node" }
}
Write-Host "done: npm view @balq/node@$version"
